/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Session */
        post: operations["join_session_v1_sessions__session_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_v1_sessions__session_id__events_get"];
        put?: never;
        /** Append Event */
        post: operations["append_event_v1_sessions__session_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rollback */
        post: operations["rollback_v1_sessions__session_id__rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to session event stream (WebSocket)
         * @description WebSocket endpoint. Upgrade from HTTP GET. Server pushes SessionEvent JSON objects after each append. Not a plain HTTP GET despite OpenAPI listing.
         */
        get: operations["stream_session_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Actor */
        Actor: {
            kind: components["schemas"]["ActorKind"];
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["ParticipantRole"];
        };
        /**
         * ActorKind
         * @enum {string}
         */
        ActorKind: "human" | "agent" | "system";
        /** AppendEventResponse */
        AppendEventResponse: {
            /** Event Id */
            event_id: string;
            /** Seq */
            seq: number;
        };
        /** Causality */
        Causality: {
            /** Parent Event */
            parent_event?: string | null;
            /** Root Instruction */
            root_instruction?: string | null;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Title */
            title: string;
            /** Scenario Id */
            scenario_id?: string | null;
        };
        /** CreateSessionResponse */
        CreateSessionResponse: {
            /** Session Id */
            session_id: string;
            /** Join Code */
            join_code: string;
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "doc_update" | "instruction" | "agent_step" | "tool_call" | "tool_result" | "interrupt" | "handoff" | "rollback" | "join" | "leave" | "arbitration" | "rejected";
        /** EventsPage */
        EventsPage: {
            /** Events */
            events: components["schemas"]["SessionEvent"][];
            /** Next Seq */
            next_seq: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Ok
             * @default true
             * @constant
             * @enum {boolean}
             */
            ok: true;
            /** Version */
            version: string;
        };
        /** JoinSessionRequest */
        JoinSessionRequest: {
            /** Join Code */
            join_code: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["ParticipantRole"];
        };
        /** JoinSessionResponse */
        JoinSessionResponse: {
            /** Participant Id */
            participant_id: string;
            /** Snapshot */
            snapshot: Record<string, unknown>;
            /** Catchup Summary */
            catchup_summary?: string | null;
        };
        /**
         * Labels
         * @description Annotation fields. Null in production; written by annotators.
         */
        Labels: {
            /** Serves Participant */
            serves_participant?: string | null;
            /** Conflict Group */
            conflict_group?: string | null;
            /** Conflict Resolution */
            conflict_resolution?: string | null;
            /** Mast Failure */
            mast_failure?: string | null;
        };
        /**
         * ParticipantRole
         * @enum {string}
         */
        ParticipantRole: "author" | "reviewer" | "observer";
        /** RollbackRequest */
        RollbackRequest: {
            /** To Seq */
            to_seq: number;
        };
        /** RollbackResponse */
        RollbackResponse: {
            /** Snapshot */
            snapshot: Record<string, unknown>;
            /** Rolled Back Events */
            rolled_back_events: components["schemas"]["SessionEvent"][];
        };
        /**
         * SessionEvent
         * @description Append-only event. seq is assigned by the session service on write.
         */
        SessionEvent: {
            /** Event Id */
            event_id: string;
            /** Session Id */
            session_id: string;
            /** Seq */
            seq?: number | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            actor: components["schemas"]["Actor"];
            type: components["schemas"]["EventType"];
            /** Payload */
            payload: Record<string, unknown>;
            causality?: components["schemas"]["Causality"];
            labels?: components["schemas"]["Labels"] | null;
        };
        /**
         * SessionEventCreate
         * @description Client write shape: seq is allocated server-side.
         */
        SessionEventCreate: {
            /** Event Id */
            event_id?: string | null;
            actor: components["schemas"]["Actor"];
            type: components["schemas"]["EventType"];
            /** Payload */
            payload: Record<string, unknown>;
            causality?: components["schemas"]["Causality"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_session_v1_sessions__session_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_v1_sessions__session_id__events_get: {
        parameters: {
            query?: {
                since?: number;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    append_event_v1_sessions__session_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionEventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppendEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollback_v1_sessions__session_id__rollback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    stream_session_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols (WebSocket) */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
